services:
  - type: web
    name: streamlit-tensor-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000
    plan: free
